package entities;
// Generated Nov 21, 2016 3:22:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adId;
     private String adName;
     private Integer adLevel;
     private AdminPassword adminPassword;
     private Set adminAccountFrozenLogs = new HashSet(0);
     private Set adminMomentsReviewLogs = new HashSet(0);
     private Set adminCommentReviewLogs = new HashSet(0);

    public Admin() {
    }

    public Admin(String adName, Integer adLevel, AdminPassword adminPassword, Set adminAccountFrozenLogs, Set adminMomentsReviewLogs, Set adminCommentReviewLogs) {
       this.adName = adName;
       this.adLevel = adLevel;
       this.adminPassword = adminPassword;
       this.adminAccountFrozenLogs = adminAccountFrozenLogs;
       this.adminMomentsReviewLogs = adminMomentsReviewLogs;
       this.adminCommentReviewLogs = adminCommentReviewLogs;
    }
   
    public Integer getAdId() {
        return this.adId;
    }
    
    public void setAdId(Integer adId) {
        this.adId = adId;
    }
    public String getAdName() {
        return this.adName;
    }
    
    public void setAdName(String adName) {
        this.adName = adName;
    }
    public Integer getAdLevel() {
        return this.adLevel;
    }
    
    public void setAdLevel(Integer adLevel) {
        this.adLevel = adLevel;
    }
    public AdminPassword getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(AdminPassword adminPassword) {
        this.adminPassword = adminPassword;
    }
    public Set getAdminAccountFrozenLogs() {
        return this.adminAccountFrozenLogs;
    }
    
    public void setAdminAccountFrozenLogs(Set adminAccountFrozenLogs) {
        this.adminAccountFrozenLogs = adminAccountFrozenLogs;
    }
    public Set getAdminMomentsReviewLogs() {
        return this.adminMomentsReviewLogs;
    }
    
    public void setAdminMomentsReviewLogs(Set adminMomentsReviewLogs) {
        this.adminMomentsReviewLogs = adminMomentsReviewLogs;
    }
    public Set getAdminCommentReviewLogs() {
        return this.adminCommentReviewLogs;
    }
    
    public void setAdminCommentReviewLogs(Set adminCommentReviewLogs) {
        this.adminCommentReviewLogs = adminCommentReviewLogs;
    }




}


