package entities;
// Generated Nov 7, 2016 2:03:08 PM by Hibernate Tools 4.3.1



/**
 * AdminPassword generated by hbm2java
 */
public class AdminPassword  implements java.io.Serializable {


     private Integer admId;
     private Admin admin;
     private String admPwd;

    public AdminPassword() {
    }

	
    public AdminPassword(Admin admin) {
        this.admin = admin;
    }
    public AdminPassword(Admin admin, String admPwd) {
       this.admin = admin;
       this.admPwd = admPwd;
    }
   
    public Integer getAdmId() {
        return this.admId;
    }
    
    public void setAdmId(Integer admId) {
        this.admId = admId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public String getAdmPwd() {
        return this.admPwd;
    }
    
    public void setAdmPwd(String admPwd) {
        this.admPwd = admPwd;
    }




}


