package entities;
// Generated Nov 21, 2016 3:22:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AdminMomentsReviewLog generated by hbm2java
 */
public class AdminMomentsReviewLog  implements java.io.Serializable {


     private int adtMomentId;
     private Admin admin;
     private Moments moments;
     private UserInfo userInfo;
     private Date admMomentRemoveTime;
     private String admMomentRemoveMsg;

    public AdminMomentsReviewLog() {
    }

	
    public AdminMomentsReviewLog(Moments moments) {
        this.moments = moments;
    }
    public AdminMomentsReviewLog(Admin admin, Moments moments, UserInfo userInfo, Date admMomentRemoveTime, String admMomentRemoveMsg) {
       this.admin = admin;
       this.moments = moments;
       this.userInfo = userInfo;
       this.admMomentRemoveTime = admMomentRemoveTime;
       this.admMomentRemoveMsg = admMomentRemoveMsg;
    }
   
    public int getAdtMomentId() {
        return this.adtMomentId;
    }
    
    public void setAdtMomentId(int adtMomentId) {
        this.adtMomentId = adtMomentId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Moments getMoments() {
        return this.moments;
    }
    
    public void setMoments(Moments moments) {
        this.moments = moments;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public Date getAdmMomentRemoveTime() {
        return this.admMomentRemoveTime;
    }
    
    public void setAdmMomentRemoveTime(Date admMomentRemoveTime) {
        this.admMomentRemoveTime = admMomentRemoveTime;
    }
    public String getAdmMomentRemoveMsg() {
        return this.admMomentRemoveMsg;
    }
    
    public void setAdmMomentRemoveMsg(String admMomentRemoveMsg) {
        this.admMomentRemoveMsg = admMomentRemoveMsg;
    }




}


