package entities;
// Generated Nov 7, 2016 2:03:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer comtId;
     private Comments comments;
     private Moments moments;
     private UserInfo userInfo;
     private String comtContent;
     private Date comtTime;
     private Integer comtVisable;
     private AdminCommentReviewLog adminCommentReviewLog;
     private Set commentses = new HashSet(0);

    public Comments() {
    }

    public Comments(Comments comments, Moments moments, UserInfo userInfo, String comtContent, Date comtTime, Integer comtVisable, AdminCommentReviewLog adminCommentReviewLog, Set commentses) {
       this.comments = comments;
       this.moments = moments;
       this.userInfo = userInfo;
       this.comtContent = comtContent;
       this.comtTime = comtTime;
       this.comtVisable = comtVisable;
       this.adminCommentReviewLog = adminCommentReviewLog;
       this.commentses = commentses;
    }
   
    public Integer getComtId() {
        return this.comtId;
    }
    
    public void setComtId(Integer comtId) {
        this.comtId = comtId;
    }
    public Comments getComments() {
        return this.comments;
    }
    
    public void setComments(Comments comments) {
        this.comments = comments;
    }
    public Moments getMoments() {
        return this.moments;
    }
    
    public void setMoments(Moments moments) {
        this.moments = moments;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getComtContent() {
        return this.comtContent;
    }
    
    public void setComtContent(String comtContent) {
        this.comtContent = comtContent;
    }
    public Date getComtTime() {
        return this.comtTime;
    }
    
    public void setComtTime(Date comtTime) {
        this.comtTime = comtTime;
    }
    public Integer getComtVisable() {
        return this.comtVisable;
    }
    
    public void setComtVisable(Integer comtVisable) {
        this.comtVisable = comtVisable;
    }
    public AdminCommentReviewLog getAdminCommentReviewLog() {
        return this.adminCommentReviewLog;
    }
    
    public void setAdminCommentReviewLog(AdminCommentReviewLog adminCommentReviewLog) {
        this.adminCommentReviewLog = adminCommentReviewLog;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


