package entities;
// Generated Nov 7, 2016 4:37:39 PM by Hibernate Tools 4.3.1



/**
 * Follows generated by hbm2java
 */
public class Follows  implements java.io.Serializable {


     private int followedId;
     private UserInfo userInfoByFollowerId;
     private UserInfo userInfoByUsrId;

    public Follows() {
    }

    public Follows(UserInfo userInfoByFollowerId, UserInfo userInfoByUsrId) {
       this.userInfoByFollowerId = userInfoByFollowerId;
       this.userInfoByUsrId = userInfoByUsrId;
    }
   
    public int getFollowedId() {
        return this.followedId;
    }
    
    public void setFollowedId(int followedId) {
        this.followedId = followedId;
    }
    public UserInfo getUserInfoByFollowerId() {
        return this.userInfoByFollowerId;
    }
    
    public void setUserInfoByFollowerId(UserInfo userInfoByFollowerId) {
        this.userInfoByFollowerId = userInfoByFollowerId;
    }
    public UserInfo getUserInfoByUsrId() {
        return this.userInfoByUsrId;
    }
    
    public void setUserInfoByUsrId(UserInfo userInfoByUsrId) {
        this.userInfoByUsrId = userInfoByUsrId;
    }




}


