package entities;
// Generated Nov 7, 2016 2:03:08 PM by Hibernate Tools 4.3.1



/**
 * GroupMembers generated by hbm2java
 */
public class GroupMembers  implements java.io.Serializable {


     private int gpmId;
     private Group group;
     private UserInfo userInfo;

    public GroupMembers() {
    }

	
    public GroupMembers(Group group) {
        this.group = group;
    }
    public GroupMembers(Group group, UserInfo userInfo) {
       this.group = group;
       this.userInfo = userInfo;
    }
   
    public int getGpmId() {
        return this.gpmId;
    }
    
    public void setGpmId(int gpmId) {
        this.gpmId = gpmId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


