package entities;
// Generated Nov 21, 2016 3:22:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Likes generated by hbm2java
 */
public class Likes  implements java.io.Serializable {


     private Integer likId;
     private Moments moments;
     private UserInfo userInfo;
     private Date likTime;

    public Likes() {
    }

    public Likes(Moments moments, UserInfo userInfo, Date likTime) {
       this.moments = moments;
       this.userInfo = userInfo;
       this.likTime = likTime;
    }
   
    public Integer getLikId() {
        return this.likId;
    }
    
    public void setLikId(Integer likId) {
        this.likId = likId;
    }
    public Moments getMoments() {
        return this.moments;
    }
    
    public void setMoments(Moments moments) {
        this.moments = moments;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public Date getLikTime() {
        return this.likTime;
    }
    
    public void setLikTime(Date likTime) {
        this.likTime = likTime;
    }




}


